baseURL: "https://tanookizoot.com"
languageCode: "en-us"
title: "TanookiZoot"
theme: hugo-profile

Paginate: 3
disqusShortname: tanookizoot
googleAnalytics: G-ET77RHBLNH

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #  title: Example dropdown menu
    #  name: Dropdown
    #  weight: 2
    #- identifier: dropdown1
    #  title: example dropdown 1
    #  name: example 1
    #  url: /#
    #  parent: dropdown
    #  weight: 1
    #- identifier: dropdown2
    #  title: example dropdown 2
    #  name: example 2
    #  url: /#
    #  parent: dropdown
    #  weight: 2

params:
  title: "TanookiZoot"
  description: Hi, I'm TanookiZoot!
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/zootface300.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "TanookiZoot."
    subtitle: "I play games and cultivate chill vibes"
    content: "A variety streamer who plays games, shares stories, and listens to the folks around him. "
    image: /images/TanookiZootBlackBG.gif
    button:
      enable: false
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-twitch
          url: https://twitch.tv/tanookizoot
        - icon: fab fa-twitter
          url: https://twitter.com/TanookiZoot
        - icon: fab fa-steam
          url: https://steamcommunity.com/id/TanookiZoot
        - icon: fab fa-discord
          url: https://discord.gg/qbUWcggk
      customIcons:
        - icon: /images/projects/kofilogo_bluebg.png
          url: "https://ko-fi.com/tanookizoot"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/coat14.png"
    content: |-
      I am a variety streamer on Twitch. I do cool stuff and help create chill vibes.
    skills:
      enable: true
      title: "Here are a few games that I've been playing recently:"
      items:
        - Valheim
        - No Man's Sky
        - Undermine
        - Core Keeper
        - Streets of Rogue
        - Boomerang Fu

  # Experience
  experience:
    enable: false
    items:
      - job: "Senior Software Developer"
        company: "Facebook"
        companyUrl: "https://example.com"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Software Developer"
        company: "Amazon"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

     

  # Education
  education:
    enable: false
    # index: true
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing eli. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Black Belt - Boomerang Fu
        content: Area of expertise- Telekenesis
        url: https://www.boomerangfu.com/
      - title: Ancient Fruit Wine Maven - Stardew Valley
        content: Highly popular artisinal farmer.  Grandfather-approved.
        url: https://www.stardewvalley.net/
      - title: Completed Cloakroom - Heave Ho
        content: Fashionably attired.
        url: "https://www.heavehogame.com/"
      - title: Novice Gardener - Core Keeper
        content: Grower of glow tulips and assorted plants
        url: "https://pugstorm.eu/"
      - title: Fridge Hacker - Streets of Rogue
        content: Is your refrigerator running?
        url: https://streetsofrogue.com/

  # projects
  projects:
    enable: true
    items:
      - title: Extra Life
        content: I stream sometimes to raise money for Extra Life, a program of Children's Miracle Network Hospitals.
        image: /images/projects/ExtraLife_logo_RGB.svg
        featured:
          name: My Team
          link: https://www.extra-life.org/index.cfm?fuseaction=donorDrive.team&teamID=60690
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        # links:
        #  - icon: fa fa-envelope
        #    url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #  - icon: fab fa-github
        #    url: https://github.com/gurusabarish/hugo-profile
        #  - icon: fab fa-twitter
        #    url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: The Beanpod
        content: Sometimes I hang out on Discord with a bunch of cool folks.  We call ourselves the Beanpod.
        image: /images/projects/beanpod.webp
        featured:
          name: Discord Link
          link: https://discord.gg/qbUWcggk
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        # links:
        #  - icon: fab fa-github
        #    url: https://github.com/gurusabarish/converter

      # - title: Hugo Profile V2
      #  content: A clean and simple Hugo template for personal portfolio and blog.
      #  image: /images/projects/profile2.jpg
      #  featured:
      #    name: Demo V2
      #    link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
      #  links:
      #    - icon: fab fa-github
      #      url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: hello@tanookizoot.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/tanookizoot
      # linkedin: https://linkedin.com
      twitter: https://twitter.com/TanookiZoot
      # instagram: https://instagram.com
      # facebook: https://facebook.com