name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      
jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: hugo-deploy-gh-pages
      uses: khanhicetea/gh-actions-hugo-deploy-gh-pages@master
      env:
        GITHUB_REMOTE_REPOSITORY: "tanookizoot/tanookizoot.github.io"
        GITHUB_BRANCH: main
        GIT_DEPLOY_KEY: ${{ secrets.TANOOKI_DEPLOY }}
        HUGO_VERSION: "0.95.0"
